### ISSUE TITLE
Bytes Team Project Verification after Sprint 1

### ISSUE THREAD

**Issue by kelvinzheng3317** [teamup-apps-for-good/fin-lit-quest#46]
### **Project Verification Sprint 1**

Team: Bytes
Verifying: FinLitQuest

**Getting Started**
The documentation has proper instructions for how to set up the project including how to install dependencies and initialize the database.

**Running Tests**
The documentation does properly cover how to run the tests. Majority of tests exist but a few small areas of code are missing tests. All currently existing tests are passing and achieve more than 90% coverage (97.09%).

**Deploying**
The documentation has proper easy to follow instructions for deploying the application to Heroku. Everything worked correctly and after deployment, all functionalities that are supposed to exist do exist.

**How to Contact**
The documentation does cover how to contact the team regarding an issue. There is some documentation on troubleshooting, mainly in regards to resetting the database but that is about it. Possible improvements include including a contact email and more troubleshooting documentation.

Other Notes
The back button not actually going back to the previous page can be a bit confusing for users. This is most clearly seen from the “Hello Player!” page where clicking on “inventory” then “back” takes you to the “character profile” page instead of back to “Hello Player!”. This is a minor issue though and address it as you wish.
There is a minor typo in the documentation. “Resetting the Database” is written as “Resetting the Databse”.

**Comment by jacksors** [comment]
Thanks for the feedback!
